version: '3'

services:
    web:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/app/
        links:
            - php
            - db

    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - .:/app/
        links:
            - db

    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - ./data/db:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
